# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b037d1a2f0b8e18c30e09dc046d97b930df0538b65a93b65cde409878b0bc08b54ee9ae15df2c26088066f0406eb34db3498c2989a4e66b8750d3b4c2845bd87

test:
  secret_key_base: f75b2b948dc0ed800ace16bd7b75b6bde3fec6c58968276012804279939923f3a905135d3610e96b5e318e09d231426cca6b9b7700478dd2b986a370c8b79eb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
